# Generated by Django 3.2 on 2021-04-27 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='solution',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.TextField(choices=[('WAIT', 'Waiting for check'), ('QUEUED', 'Queued'), ('IN PROGRESS', 'In progress'), ('FAILED', 'Check failed'), ('SUCCESS', 'Check success')], default='WAIT'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict',
            field=models.TextField(choices=[('NO VERDICT', 'No verdict'), ('WRONG FILE FORMAT', 'Wrong format of file'), ('FILE TOO BIG', 'File has too large size'), ('BUILD FAILED', 'Build failed'), ('RUNTIME ERROR', 'Runtime error'), ('TIME LIMIT ERROR', 'Time limit error'), ('MEMORY LIMIT ERROR', 'Memory limit error'), ('WRONG ANSWER', 'Wrong answer'), ('CORRECT SOLUTION', 'Correct solution')], default='NO VERDICT'),
        ),
        migrations.AddField(
            model_name='solution',
            name='verdict_text',
            field=models.TextField(blank=True, default='Посылка не проверена'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='language',
            field=models.TextField(choices=[('ASM', 'GNU Assembly Language'), ('C99', 'GNU GCC C99'), ('C11', 'GNU GCC C11'), ('C++11', 'GNU G++ C++ 11'), ('C++14', 'GNU G++ C++ 14'), ('C++17', 'GNU G++ C++ 17'), ('C++20', 'GNU G++ C++ 20'), ('Python2', 'Python v2.7'), ('Python3', 'Python v3.9.4')]),
        ),
    ]
