# Generated by Django 3.2 on 2021-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210427_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
