# Generated by Django 3.2 on 2021-04-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_solution_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='code',
        ),
        migrations.AddField(
            model_name='codefile',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
