# Generated by Django 3.2 on 2021-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210427_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='node',
            field=models.IntegerField(default=1),
        ),
    ]
