# Generated by Django 3.2 on 2021-05-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_solution_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracttask',
            name='grading_system',
            field=models.TextField(choices=[('BINARY', 'Accepted or failed'), ('BINARY TEST', '1 Point for each test'), ('POINTS TEST', 'N points for each test')], default='BINARY'),
        ),
        migrations.AddField(
            model_name='solution',
            name='event_type',
            field=models.TextField(choices=[('USER_SOLUTION', 'User solution to task'), ('TASK_VALIDATION', 'Validation of authors task (all tests)')], default='USER_SOLUTION'),
        ),
        migrations.AddField(
            model_name='test',
            name='max_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solution',
            name='verdict',
            field=models.TextField(choices=[('NO VERDICT', 'No verdict'), ('WRONG FILE FORMAT', 'Wrong format of file'), ('FILE TOO BIG', 'File has too large size'), ('BUILD FAILED', 'Build failed'), ('RUNTIME ERROR', 'Runtime error'), ('TIME LIMIT ERROR', 'Time limit error'), ('MEMORY LIMIT ERROR', 'Memory limit error'), ('WRONG ANSWER', 'Wrong answer'), ('PARTIAL SOLUTION', 'Partial solution'), ('CORRECT SOLUTION', 'Correct solution')], default='NO VERDICT'),
        ),
    ]
