# Generated by Django 3.2 on 2021-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20210504_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
