# Generated by Django 3.2 on 2021-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_solution_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('pk',)},
        ),
    ]
