# Generated by Django 3.2 on 2021-05-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_codefile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='language',
            field=models.TextField(choices=[('ASM', 'GNU Assembly Language'), ('C99', 'GNU GCC C99'), ('C11', 'GNU GCC C11'), ('C++11', 'GNU G++ C++ 11'), ('C++14', 'GNU G++ C++ 14'), ('C++17', 'GNU G++ C++ 17'), ('C++20', 'GNU G++ C++ 20'), ('Python2', 'Python v2.7'), ('Python3', 'Python v3.9.4'), ('Java8', 'Java 8')]),
        ),
    ]
