# Generated by Django 3.2 on 2021-05-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(upload_to='channel_preview_images/')),
                ('cover_image', models.ImageField(blank=True, upload_to='channel_cover_images/')),
                ('channel_description', models.TextField(blank=True)),
                ('owner_full_name', models.CharField(max_length=200)),
                ('owner_photo', models.ImageField(upload_to='channel_owner_photos/')),
                ('owner_interview', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
