# Generated by Django 3.2 on 2021-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='background_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='channel',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='channel_background_images/'),
        ),
    ]
