# Generated by Django 3.2 on 2021-05-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20210518_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(default=models.CharField(max_length=150), max_length=100, unique=True)),
                ('theme', models.TextField(choices=[('ARITHMETIC', 'Арифметика'), ('MATH', 'Математика'), ('ALGEBRA', 'Алгебра'), ('CALCULUS', 'Математический анализ'), ('T_W_I_M_S', 'Теория вероятностей и математическая статистика'), ('DISCRETE_MATH', 'Дискретная математика'), ('NUMBER_THEORY', 'Теория чисел'), ('WEB', 'Web-Программирование'), ('DATA_SCIENCE', 'Data science / Наука о данных'), ('NEURAL_MACHINE', 'Нейронные сети и машинное обучение'), ('ALGORITHMS', 'Алгоритмы и структуры данных'), ('MOBILE', 'Мобильная разработка'), ('TESTING', 'Тестирование'), ('DEV_OPS', 'DevOps'), ('MANAGEMENT', 'Менеджмент'), ('BUSINESS', 'Бизнес'), ('FOREIGN_LANGUAGES', 'Иностранные языки'), ('NONE', 'Без направления')], default='NONE')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('preview_picture', models.ImageField(blank=True, upload_to='course_preview_images/')),
                ('main_picture', models.ImageField(blank=True, upload_to='course_main_pictures/')),
                ('channel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.channel')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='own_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
