# Generated by Django 3.2 on 2021-05-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='course_description_block_images/')),
                ('image_position', models.TextField(choices=[('LEFT', 'Слева от текста'), ('UP', 'Сверху над текстом'), ('DOWN', 'Снизу под текстом'), ('RIGHT', 'Справа от текста')], default='LEFT')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_blocks', to='courses.course')),
            ],
        ),
    ]
