# Generated by Django 3.2 on 2021-05-18 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedescriptionblock',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='coursedescriptionblock',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='ModuleDescriptionListElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_elements', to='courses.module')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
