# Generated by Django 3.1.1 on 2021-05-23 09:31

from django.conf import settings
from django.db import migrations, models
import management.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20210520_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_in_channel_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='order',
            field=management.fields.OrderField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coursedescriptionblock',
            name='order',
            field=management.fields.OrderField(blank=True, default=1),
        ),
    ]
