# Generated by Django 3.2.3 on 2021-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210521_0127'),
    ]

    operations = [

    ]
