# Generated by Django 3.1.1 on 2021-05-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210523_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='show_in_channel_page',
            new_name='show_course_in_channel_page',
        ),
    ]
