# Generated by Django 3.2.3 on 2021-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_show_in_channel_page'),
        ('courses', '0012_auto_20210523_1238'),
    ]

    operations = [
    ]
