# Generated by Django 3.2.3 on 2021-05-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='user',
        ),
    ]
