# Generated by Django 3.2.3 on 2021-05-28 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_auto_20210528_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='contests', to='courses.CourseTask'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.contest'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestsolution',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contest_solutions', to='courses.contestparticipant'),
        ),
        migrations.AddField(
            model_name='coursesolution',
            name='course_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_solutions', to='courses.coursetask'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 13, 48, 52, 348667)),
        ),
    ]
