# Generated by Django 3.2.3 on 2021-05-28 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210528_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.TextField(choices=[('WAIT', 'Ожидается начало контеста.'), ('ACTIVE', 'В данный момент контест идет.'), ('FINISHED', 'Контест завершен. ')], default='WAIT'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 13, 59, 0, 612155)),
        ),
    ]
