# Generated by Django 3.2.3 on 2021-05-28 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210528_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='solution_file_raw',
            field=models.FileField(default=None, upload_to='course_files/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 28, 41, 982934)),
        ),
    ]
