# Generated by Django 3.2.3 on 2021-05-28 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210528_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='solution_file_lang',
            field=models.TextField(choices=[('ASM', 'GNU Assembly Language'), ('C99', 'GNU GCC C99'), ('C11', 'GNU GCC C11'), ('C++11', 'GNU G++ C++ 11'), ('C++14', 'GNU G++ C++ 14'), ('C++17', 'GNU G++ C++ 17'), ('C++20', 'GNU G++ C++ 20'), ('Python2', 'Python v2.7'), ('Python3', 'Python v3.9.4'), ('Java8', 'Java 8')], default='C++14'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 33, 3, 820931)),
        ),
    ]
